<?php

namespace ProviderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{
    public function findProviders()
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.deleted = :deleted')
            ->setParameter('deleted', 0)
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * @param $email
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findProvidersByEmail($email)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.email = :email')
            ->andWhere('a.deleted = :deleted')
            ->setParameter('email', $email)
            ->setParameter('deleted', 0)
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }

    /**
     * @param $string String
     * @param $expiration Integer
     * @return String
     */
    public function generateToken($string='', $expiration=14400)
    {
        if (!$string)
            return '';

        try {
            return $this->get('lexik_jwt_authentication.encoder')
                ->encode([
                    'username' => $string,
                    'exp' => time() + $expiration
                ]);
        } catch (Exception $e) {
            throw $e->getMessage();
        }
    }
}
