<?php

namespace ProviderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{
    public function findProviders()
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.deleted = :deleted')
            ->setParameter('deleted', 0)
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * @param $email
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findProvidersByEmail($email)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.email = :email')
            ->andWhere('a.deleted = :deleted')
            ->setParameter('email', $email)
            ->setParameter('deleted', 0)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
