authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation
    prefix:   /

provider:
    resource: "@ProviderBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#app_register:
#    path:     /recognition/reply
#    defaults: { _controller: DitttoRecognitionBundle:Default:recogniseBack }
